name: Lint and Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$short_sha" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: timee98642
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: timee98642/petal-api:${{ env.COMMIT_SHORT_SHA }}
